name: posts
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-141.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  kiwi: ^4.0.2
  localstore: ^1.2.3
  flutter_svg: ^1.1.1+1
  uuid: ^3.0.6
  intl: ^0.17.0
  validators: ^3.0.0
  masked_text_field: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
